name: FFA
main: FFA\Main

api: 5.0.0
version: 1.0.0

author: sheluvmyshe
description: FFA's plugin for PMMP 5.x (beta-version)

load: POSTWORLD
website: https://github.com/luckpickme/ffa

commands:
  ffa:
    description: "Join FFA arena"
    usage: "/ffa <mode>"
    aliases: ["freeforall"]
  lang:
    description: "Change your language"
    usage: "/lang <language>"
    aliases: ["language", "ffalang"]

permissions:
  ffa.command.use:
    description: "Allows to use FFA commands"
    default: true
  ffa.command.lang:
    description: "Allows to change language"
    default: true