# made by sheluvmyshe (github.com/luckpickme)
arenas:
  nodebuff1:
    type: "nodebuff"
    world: "ffa_nodebuff"
    spawn:
      x: 100.5
      y: 64
      z: 200.5
      yaw: 90
      pitch: 0
  sumo1:
    type: "sumo"
    world: "ffa_sumo"
    spawn:
      x: 50.5
      y: 70
      z: 50.5
      yaw: 0
      pitch: 0

kits:
  nodebuff:
    sword:
      type: "diamond_sword"
      enchantments:
        sharpness: 2
    potions:
      - type: "healing"
        count: 3
      - type: "fire_resistance"
        count: 3
    golden_apples: 8